# Generated by Django 3.2.25 on 2025-03-08 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_contact_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='InquiryForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.CharField(max_length=15)),
                ('comment', models.TextField()),
            ],
            options={
                'db_table': 'inquiry_form',
            },
        ),
    ]
